SilverStripe\SiteConfig\SiteConfig:
  # Charset
  CharsetStatus: true
  Charset: 'UTF-8'
  # Title
  TitleStatus: true
  # Canonical
  CanonicalStatus: true
  # Custom Metadata
#  ExtraMetaStatus: true
