---
Name: 'SEO_Metadata'
Ater:
    - 'framework/*'
    - 'cms/*'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'SEO_Metadata_SiteConfig_DataExtension'

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'SEO_Metadata_SiteTree_DataExtension'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'silverstripe-seo-metadata/css/LeftAndMain.css'
