---
Name: 'SEO_Metadata'
---
SiteConfig:
  extensions:
    - 'SEO_Metadata_SiteConfig_DataExtension'

SiteTree:
  extensions:
    - 'SEO_Metadata_SiteTree_DataExtension'

LeftAndMain:
  extra_requirements_css:
    - 'silverstripe-seo-metadata/css/LeftAndMain.css'
